---
- apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present
    #when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

#- apt_repository:
#    repo: deb http://download.virtualbox.org/virtualbox/debian zesty contrib
#    state: present
#    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '17.10'

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Essentials | Ensure that the repositories are update
  apt:
    update_cache: yes

- name: Essentials | Install all the essential packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - virtualbox-5.2
